### ISSUE TITLE
Appliances not loading

### ISSUE THREAD

**Issue by martyncoup** [yannickdils/AzureMigrateOperations#1]
The template appears to run fine, however when I visit the appliances page, it never loads. Is this something you have seen before?

**Comment by martyncoup** [comment]
I fixed this, looks like you need to generate the certificate in the Key Vault first before you continue. Then the page loads successfully.

**Comment by roshnew** [comment]
@martyncoup , Can you please explain in  bit more detail how you fixed this issue, I am facing same issue.
